Now ignores .gz, .zip, .npy, part-* files except in small_data
thedataincubator/nbzip pull request #1
Opened 2021-03-15 19:14 UTC by RichardOtt

This is a possible option for fixing the "download as zip button breaks" problems. It's not as elegant as moving downloaded files to some master download directory that we ignore, but requires no change to the notebooks, and possibly prevents future issues if someone forgets and downloads to the wrong place.

2021-03-20 01:19 UTC, RichardOtt commented
The latest version reads `~/.ipython/nbzip.json` (it actually checks to see where ipython thinks it should go, which is maybe not the best plan, but should be fine on our systems).  It takes a json config of the form
{ 'exclude': [list of regexes], 'include': [list of regexes]}
if a file matches an exclude, it is excluded unless it also matches an include.  It defaults to the previous hard-coded values if no config file is present

Concerns about it:
- We can easily screw up a regex in a file, and it will cause strange errors
- These are _regexes_, not _globs_, and that difference matters
- It reloads the config file at server startup, we could change that to zip run time

2021-03-22 17:55 UTC, rschroll requested changes
The problem with short PRs is that I can understand them, and then have opinions.

2021-03-22 17:55 UTC, rschroll commented on nbzip/handlers.py
> +config_path = IPython.paths.get_ipython_dir()
How about `jupyter_core.paths.jupyter_config_dir()`.  Or if we want to get fancy, going through all of `jupyter_core.paths.jupyter_config_path()`.

2021-03-22 17:55 UTC, rschroll commented on nbzip/handlers.py
> +              'include': ['.*small_data/.*']}
I understand the idea here, but I worry that this will make it difficult to debug.  "I deleted the config file, but it's still ignoring my .gz files."  I think I'd just go with an empty config here.

2021-03-22 17:55 UTC, rschroll commented on nbzip/handlers.py
> +            keep = False
We could short-circuit with a continue here.  This would also let you add an else clause to skip the entire second loop if nothing matches in the exclude patterns.

Alternatively, `keep = not any(re.fullmatch() for exclude in config['exclude'])`, which should also short-circuit.

2021-03-22 17:55 UTC, rschroll commented on nbzip/handlers.py
> +    for exclude in config['exclude']:
We either need to make sure the config has an exclude parameter above, or use `config.get('exclude', [])` here.

2021-03-22 18:00 UTC, rschroll commented
Re the concern about regexes vs globs: `glob` is in the stdlib, I believe.

2021-03-22 18:51 UTC, RichardOtt commented on nbzip/handlers.py
> +              'include': ['.*small_data/.*']}
My only concern is that we then have to make sure we deploy a config file - so we'll need to update the Dockerfile (right?)

2021-03-22 18:52 UTC, RichardOtt commented on nbzip/handlers.py
> +    for exclude in config['exclude']:
good catch

2021-03-22 18:54 UTC, rschroll commented on nbzip/handlers.py
> +              'include': ['.*small_data/.*']}
Yes.  But we need to do that anyway to get the new version of nbzip on it.

2021-03-22 20:17 UTC, RichardOtt commented on nbzip/handlers.py
> +config_path = IPython.paths.get_ipython_dir()
Sure, we can switch to the jupyter config dir instead.  I don't want to go through the config path, just because then we need to worry about resolving which one has higher priority.  I'll try to take another look into hooking into their configuration system that does that for you, it must be possible

2021-03-22 20:19 UTC, RichardOtt commented on nbzip/handlers.py
> +            keep = False
We can configure these to be short circuiting, but I'm not sure that it's worth the trade in readability - I expect the short circuit will only get triggered on maybe 10% of the files, and the computational savings is very small, since most of the work here is adding things to the zip file.

2021-03-22 21:38 UTC, RichardOtt commented on nbzip/handlers.py
> +            keep = False
I added a continue and a check in the second loop - it won't fully skip the loop, but will only perform a boolean check instead of regex for each possible include

2021-03-22 23:42 UTC, rschroll approved these changes
Looks good.  And now I know about fnmatch.

Should we load the config file inside of the Handler?

2021-03-23 00:33 UTC, RichardOtt commented
Superseded by https://github.com/thedataincubator/nbzip/pull/2

2021-03-23 00:33 UTC, closed without merging